### ISSUE TITLE
NameError: name 'settings' is not defined

### ISSUE THREAD

**Issue by echan00** [agubelu/discord-bot-template#5]
```
Traceback (most recent call last):
  File "your_bot.py", line 5, in <module>
    import message_handler
  File "/Users/eee/Workspace/discord-bot/message_handler.py", line 11, in <module>
    for c in BaseCommand.__subclasses__()}
  File "/Users/eee/Workspace/discord-bot/message_handler.py", line 11, in <dictcomp>
    for c in BaseCommand.__subclasses__()}
  File "/Users/eee/Workspace/discord-bot/commands/example_command.py", line 21, in __init__
    super().__init__(description, params)
  File "/Users/eee/Workspace/discord-bot/commands/base_command.py", line 9, in __init__
    desc = f"**{settings.COMMAND_PREFIX}{self.name}**"
NameError: name 'settings' is not defined
```

What error could this be about?

**Comment by echan00** [comment]
Looks like settings.py is loaded in your_bot.py but not in base_command.py?
