### ISSUE TITLE
Waiting for reactions on events, error: "concurrent.futures._base.TimeoutError"

### ISSUE THREAD

**Issue by echan00** [agubelu/discord-bot-template#7]
I have a base command that waits and acts on user reactions with no problems:

```
class Tt(BaseCommand):

    def __init__(self):
        description = "Test Bot"
        super().__init__(description, '')

    async def handle(self, params, message, client, session):                  
        channel = get_channel(client, "general")
        msg = await channel.send(text='text')
        await msg.add_reaction(':some_emoji:')

        emoji=''
        while True:
            if emoji == ':some_emoji:':
                # do this
            res = await client.wait_for('reaction_add', timeout=60)
            if res == None:
                break
            if str(res[1]) != str(client.user):
                emoji = str(res[0].emoji)
```

When I try to post the same type of message during an event, I receive errors:

```
class some_event(BaseEvent):

    def __init__(self):
        interval_minutes = 1  # Set the interval for this event
        super().__init__(interval_minutes)

    async def run(self, client, session):                  
        channel = get_channel(client, "general")
        msg = await channel.send(text='text')
        await msg.add_reaction(':some_emoji:')

        emoji=''
        while True:
            if emoji == ':some_emoji:':
                # do this
            res = await client.wait_for('reaction_add', timeout=60)
            if res == None:
                break
            if str(res[1]) != str(client.user):
                emoji = str(res[0].emoji)
```

Error:

```
Job "some_event.run (trigger: interval[0:01:00], next run at: 2020-12-15 23:29:28 PST)" raised an exception
Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.7.9/lib/python3.7/site-packages/apscheduler/executors/base_py3.py", line 29, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/Users/xxx/Workspace/discord-bot/events/some_event.py", line 61, in run
    res = await client.wait_for('reaction_add', timeout=5)
  File "/Users/xxx/.pyenv/versions/3.7.9/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

It seems like the error occurs the second time     `res = await client.wait_for('reaction_add', timeout=5)` is run in the while loop. @agubelu, any ideas?

**Comment by echan00** [comment]
My mistake, it's a bug
